import type { Metadata } from 'next';
import Providers from '@/components/Providers';
import TopNav from '@/components/navbar/TopNav';

import './globals.css';

export const metadata: Metadata = {
  title: 'NextDating',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <TopNav />
          <main className="container mx-auto p-5">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
